version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

  postgres:
    image: postgres
    container_name: postgresql_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=booking_doctor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8000:80"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data:
